Repository actions/actions-runner-controller, pull requests merged in 2022-04, with the labels that each got.

#922 Add WorkflowJob to GitHubEventScaleUpTriggerSpec types
  api/v1alpha1/horizontalrunnerautoscaler_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/actions-runner-controller/crds/actions.summerwind.dev_horizontalrunnerautoscalers.yaml
  config/crd/bases/actions.summerwind.dev_horizontalrunnerautoscalers.yaml
  controllers/integration_test.go
Labels: enhancement

#963 feat: default scale down flag
  controllers/autoscaling_test.go
  controllers/horizontalrunnerautoscaler_controller.go
  main.go
Labels: enhancement

#1308 refactor: set sync period default to 1m
  Makefile
  README.md
  main.go
Labels: refactor

#1310 docs: highlight breaking changes are possible
  README.md
Labels: documentation
