Repository actions/actions-runner-controller, pull requests merged in 2023-04, with the labels that each got.

#2508 Update ubuntu-22.04 Dockerfile to add python user script dir
  runner/actions-runner.ubuntu-22.04.dockerfile
Labels: needs triage, community

#2488 Add description for "dockerRegistryMirror" key
  charts/actions-runner-controller/values.yaml
Labels: needs triage, community

#2375 docs: Fix typo for automatic runner scaling
  docs/automatically-scaling-runners.md
Labels: documentation, needs triage, community

#2536 Revert docker.sock path to /var/run/docker.sock
  acceptance/deploy.sh
  acceptance/deploy_runners.sh
  acceptance/testdata/runnerdeploy.envsubst.yaml
  controllers/actions.summerwind.net/new_runner_pod_test.go
  controllers/actions.summerwind.net/runner_controller.go
  test/e2e/e2e_test.go
  testing/workflow.go
Labels: community

#2520 Stricter filtering of check run completion events
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook.go
Labels: needs triage, community

#2535 Fix the default version of kube-rbac-proxy in the docs
  charts/actions-runner-controller/README.md
Labels: community

#2497 Fix GET validation for lowercase http methods
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook.go
Labels: needs triage, community

#2504 Add CR and CRB to the helm chart
  charts/actions-runner-controller/templates/actionsmetrics.role.yaml
  charts/actions-runner-controller/templates/actionsmetrics.role_binding.yaml
  charts/actions-runner-controller/templates/actionsmetrics.service.yaml
Labels: needs triage, community

#2498 Update helm chart to support actions metrics graceful termiantion
  charts/actions-runner-controller/README.md
  charts/actions-runner-controller/templates/actionsmetrics.deployment.yaml
  charts/actions-runner-controller/templates/actionsmetrics.service.yaml
  charts/actions-runner-controller/values.yaml
Labels: needs triage, community

#2464 Proposed fix for ghes org and repo runners when authorized through github app
  github/github.go
Labels: community
