Repository actions/actions-runner-controller, pull requests merged in 2023-02, with the labels that each got.

#2293 Fix manager crashloopback for ARC deployments without scaleset-related controllers
  main.go
Labels: attention, priority-0

#2119 Resolves the erroneous webhook scale down due to check runs
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook.go
Labels: needs triage

#2286 Add support for proxy
  apis/actions.github.com/v1alpha1/autoscalinglistener_types.go
  apis/actions.github.com/v1alpha1/autoscalingrunnerset_types.go
  apis/actions.github.com/v1alpha1/ephemeralrunner_types.go
  apis/actions.github.com/v1alpha1/proxy_config_test.go
  apis/actions.github.com/v1alpha1/zz_generated.deepcopy.go
  charts/actions-runner-controller-2/crds/actions.github.com_autoscalinglisteners.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_autoscalingrunnersets.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_ephemeralrunners.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_ephemeralrunnersets.yaml
  charts/auto-scaling-runner-set/templates/autoscalingrunnerset.yaml
  charts/auto-scaling-runner-set/tests/template_test.go
  charts/auto-scaling-runner-set/values.yaml
  config/crd/bases/actions.github.com_autoscalinglisteners.yaml
  config/crd/bases/actions.github.com_autoscalingrunnersets.yaml
  config/crd/bases/actions.github.com_ephemeralrunners.yaml
  config/crd/bases/actions.github.com_ephemeralrunnersets.yaml
  config/manager/kustomization.yaml
  controllers/actions.github.com/autoscalinglistener_controller.go
  controllers/actions.github.com/autoscalinglistener_controller_test.go
  controllers/actions.github.com/autoscalingrunnerset_controller.go
  controllers/actions.github.com/autoscalingrunnerset_controller_test.go
  controllers/actions.github.com/constants.go
  controllers/actions.github.com/ephemeralrunner_controller.go
  controllers/actions.github.com/ephemeralrunner_controller_test.go
  controllers/actions.github.com/ephemeralrunnerset_controller.go
  controllers/actions.github.com/ephemeralrunnerset_controller_test.go
  controllers/actions.github.com/resourcebuilder.go
  github/actions/client.go
  github/actions/client_proxy_test.go
  github/actions/multi_client.go
  github/actions/multi_client_test.go
  go.mod
  go.sum
Labels: enhancement

#2116 Documentation corrections
  TROUBLESHOOTING.md
  docs/quickstart.md
Labels: documentation

#2218 Add reposity name and full name for prometheus labels in actions metrics
  go.mod
  go.sum
  pkg/actionsmetrics/event_reader.go
Labels: needs triage

#2285 Avastancu/arc e2e test linux vm
  .github/actions/e2e-arc-test/action.yaml
  .github/workflows/e2e-test-dispatch-workflow.yaml
  .github/workflows/e2e-test-linux-vm.yaml
  Makefile
  test_e2e_arc/arc_jobs_test.go
Labels: enhancement

#2208 chart: Create actionsmetrics.secrets.yaml
  acceptance/deploy.sh
  charts/actions-runner-controller/templates/actionsmetrics.deployment.yaml
  charts/actions-runner-controller/templates/actionsmetrics.secrets.yaml
  charts/actions-runner-controller/templates/githubwebhook.deployment.yaml
  test/e2e/e2e_test.go
Labels: needs triage
