Repository actions/actions-runner-controller, pull requests merged in 2023-03, with the labels that each got.

#2333 Rename actions-runner-controller-2 and auto-scaling-runner-set helm charts
  .github/actions/e2e-arc-test/action.yaml
  .github/workflows/publish-chart.yaml
  .github/workflows/publish-runner-scale-set.yaml
  Makefile
  charts/actions-runner-controller-2/templates/manager_role_binding.yaml
  charts/gha-runner-scale-set-controller/.helmignore
  charts/gha-runner-scale-set-controller/Chart.yaml
  charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalinglisteners.yaml
  charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalingrunnersets.yaml
  charts/gha-runner-scale-set-controller/crds/actions.github.com_ephemeralrunners.yaml
  charts/gha-runner-scale-set-controller/crds/actions.github.com_ephemeralrunnersets.yaml
  charts/gha-runner-scale-set-controller/templates/NOTES.txt
  charts/gha-runner-scale-set-controller/templates/_helpers.tpl
  charts/gha-runner-scale-set-controller/templates/deployment.yaml
  charts/gha-runner-scale-set-controller/templates/leader_election_role.yaml
  charts/gha-runner-scale-set-controller/templates/leader_election_role_binding.yaml
  charts/gha-runner-scale-set-controller/templates/manager_role.yaml
  charts/gha-runner-scale-set-controller/templates/manager_role_binding.yaml
  charts/gha-runner-scale-set-controller/templates/serviceaccount.yaml
  charts/gha-runner-scale-set-controller/tests/template_test.go
  charts/gha-runner-scale-set-controller/values.yaml
  charts/gha-runner-scale-set/.helmignore
  charts/gha-runner-scale-set/Chart.yaml
  charts/gha-runner-scale-set/ci/ci-values.yaml
  charts/gha-runner-scale-set/templates/NOTES.txt
  charts/gha-runner-scale-set/templates/_helpers.tpl
  charts/gha-runner-scale-set/templates/autoscalingrunnerset.yaml
  charts/gha-runner-scale-set/templates/githubsecret.yaml
  charts/gha-runner-scale-set/templates/kube_mode_role.yaml
  charts/gha-runner-scale-set/templates/kube_mode_role_binding.yaml
  charts/gha-runner-scale-set/templates/kube_mode_serviceaccount.yaml
  charts/gha-runner-scale-set/templates/no_permission_serviceaccount.yaml
  charts/gha-runner-scale-set/tests/template_test.go
  charts/gha-runner-scale-set/tests/values.yaml
  charts/gha-runner-scale-set/values.yaml
  docs/preview/actions-runner-controller-2/README.md
  docs/preview/gha-runner-scale-set-controller/README.md
  test/platforms/aws-eks/README.md
Labels: enhancement

#2279 Adding parameter to configure the runner set name.
  apis/actions.github.com/v1alpha1/autoscalingrunnerset_types.go
  charts/gha-runner-scale-set-controller/crds/actions.github.com_autoscalingrunnersets.yaml
  charts/gha-runner-scale-set/templates/autoscalingrunnerset.yaml
  charts/gha-runner-scale-set/tests/template_test.go
  charts/gha-runner-scale-set/values.yaml
  config/crd/bases/actions.github.com_autoscalingrunnersets.yaml
  controllers/actions.github.com/autoscalinglistener_controller.go
  controllers/actions.github.com/autoscalingrunnerset_controller.go
  controllers/actions.github.com/autoscalingrunnerset_controller_test.go
  github/actions/fake/client.go
Labels: enhancement

#2275 ADR for Limit cluster role permission on Secerts.
  adrs/2023-02-10-limit-manager-role-permission.md
Labels: enhancement

#2225 feat(actionsmetrics): Add owner and workflow_name labels to workflow job metrics
  pkg/actionsmetrics/event_reader.go
  pkg/actionsmetrics/metrics.go
  pkg/actionsmetrics/webhookserver.go
Labels: needs triage

#2397 Delete renovate.json5
  .github/renovate.json5
Labels: chore

#2276 Remove list/watch secrets permission from the manager cluster role.
  charts/gha-runner-scale-set-controller/templates/manager_role.yaml
  controllers/actions.github.com/autoscalinglistener_controller.go
  controllers/actions.github.com/ephemeralrunner_controller.go
  main.go
Labels: enhancement

#2398 Allow customization of admission webhook timeout
  acceptance/deploy.sh
  charts/actions-runner-controller/templates/webhook_configs.yaml
  test/e2e/e2e_test.go
Labels: needs triage, community

#2310 Add enterprise, organization, repository, and runner labels to runnerdeployments print columns
  apis/actions.summerwind.net/v1alpha1/runnerdeployment_types.go
  charts/actions-runner-controller/crds/actions.summerwind.dev_runnerdeployments.yaml
  config/crd/bases/actions.summerwind.dev_runnerdeployments.yaml
Labels: needs triage, community

#2265 Restricting the RBAC rules on secrets
  acceptance/deploy.sh
  charts/actions-runner-controller/templates/manager_role.yaml
  charts/actions-runner-controller/templates/manager_role_binding_secrets.yaml
  charts/actions-runner-controller/templates/manager_role_secrets.yaml
  test/e2e/e2e_test.go
Labels: needs triage, community

#2377 Allow webhook server env to be set individually
  acceptance/deploy.sh
  charts/actions-runner-controller/templates/githubwebhook.deployment.yaml
  charts/actions-runner-controller/values.yaml
  test/e2e/e2e_test.go
Labels: needs triage, community

#2324 Use Docker socket via shared emptyDir instead of TCP/mTLS
  controllers/actions.summerwind.net/new_runner_pod_test.go
  controllers/actions.summerwind.net/runner_controller.go
  test/e2e/e2e_test.go
Labels: needs triage, community

#2326 Install Docker Compose v2 as a Docker CLI plugin
  runner/actions-runner-dind-rootless.ubuntu-20.04.dockerfile
  runner/actions-runner-dind-rootless.ubuntu-22.04.dockerfile
  runner/actions-runner-dind.ubuntu-20.04.dockerfile
  runner/actions-runner-dind.ubuntu-22.04.dockerfile
  runner/actions-runner.ubuntu-20.04.dockerfile
  runner/actions-runner.ubuntu-22.04.dockerfile
  test/e2e/e2e_test.go
Labels: needs triage, community
