Repository actions/actions-runner-controller, pull requests merged in 2023-05, with the labels that each got.

#2537 Update "People" section in README
  README.md
Labels: community

#2554 docs: Update github docs links under `/managing-self-hosted-runners`
  contrib/examples/actions-runner/values.yaml
  docs/about-arc.md
  docs/choosing-runner-destination.md
  docs/managing-access-with-runner-groups.md
  docs/quickstart.md
  docs/using-arc-runners-in-a-workflow.md
  docs/using-custom-volumes.md
Labels: documentation, community

#2474 Fixed scaling runners doc link
  contrib/examples/actions-runner/README.md
Labels: documentation, community

#2552 docs: use INSTALLATION_NAME
  docs/preview/gha-runner-scale-set-controller/README.md
Labels: needs triage, community, gha-runner-scale-set

#2576 Fix update runners scheduled workflow to check for container-hooks upgrades
  .github/workflows/release-runners.yaml
  .github/workflows/update-runners.yaml
  runner/Makefile
  runner/VERSION
  runner/actions-runner-dind-rootless.ubuntu-20.04.dockerfile
  runner/actions-runner-dind-rootless.ubuntu-22.04.dockerfile
  runner/actions-runner-dind.ubuntu-20.04.dockerfile
  runner/actions-runner-dind.ubuntu-22.04.dockerfile
  runner/actions-runner.ubuntu-20.04.dockerfile
  runner/actions-runner.ubuntu-22.04.dockerfile
Labels: gha-runner-scale-set

#2577 Bump chart version to v0.23.3 for ARC v0.27.4
  charts/actions-runner-controller/Chart.yaml
Labels: attention, community

#2581 Apply naming convention to workflows
  .github/workflows/arc-publish-chart.yaml
  .github/workflows/arc-publish.yaml
  .github/workflows/arc-release-runners.yaml
  .github/workflows/arc-update-runners-scheduled.yaml
  .github/workflows/arc-validate-chart.yaml
  .github/workflows/arc-validate-runners.yaml
  .github/workflows/gha-e2e-tests.yaml
  .github/workflows/gha-publish-chart.yaml
  .github/workflows/gha-validate-chart.yaml
  .github/workflows/global-publish-canary.yaml
  .github/workflows/global-run-codeql.yaml
  .github/workflows/global-run-first-interaction.yaml
  .github/workflows/global-run-stale.yaml
  docs/adrs/2023-02-02-automate-runner-updates.md
  docs/adrs/2023-03-17-workflow-improvements.md
Labels: gha-runner-scale-set

#2596 Update CONTRIBUTING.md with new contribution guidelines and release process documentation
  .gitattributes
  CONTRIBUTING.md
  docs/preview/gha-runner-scale-set-controller/README.md
  docs/preview/gha-runner-scale-set-controller/thumbnail.png
Labels: documentation

#2603 Add concurrency limits on all workflows to eliminate wasted cycles
  .github/workflows/arc-publish-chart.yaml
  .github/workflows/arc-publish.yaml
  .github/workflows/arc-release-runners.yaml
  .github/workflows/arc-validate-chart.yaml
  .github/workflows/arc-validate-runners.yaml
  .github/workflows/gha-e2e-tests.yaml
  .github/workflows/gha-publish-chart.yaml
  .github/workflows/gha-validate-chart.yaml
  .github/workflows/global-publish-canary.yaml
  .github/workflows/global-run-codeql.yaml
  .github/workflows/go.yaml
Labels: chore

#2611 Fix workflows concurrency group names
  .github/workflows/arc-validate-chart.yaml
  .github/workflows/arc-validate-runners.yaml
  .github/workflows/gha-e2e-tests.yaml
  .github/workflows/gha-validate-chart.yaml
  .github/workflows/global-run-codeql.yaml
  .github/workflows/go.yaml
Labels: gha-runner-scale-set

#2563 Fix typo in HorizontalRunnerAutoscaler
  apis/actions.summerwind.net/v1alpha1/horizontalrunnerautoscaler_types.go
  charts/actions-runner-controller/crds/actions.summerwind.dev_horizontalrunnerautoscalers.yaml
  config/crd/bases/actions.summerwind.dev_horizontalrunnerautoscalers.yaml
Labels: needs triage, community

#2606 feat: support configure docker insecure registry with env
  runner/entrypoint-dind.sh
Labels: needs triage, community

#2582 fix: labels on github webhook service template
  charts/actions-runner-controller/templates/githubwebhook.service.yaml
Labels: needs triage, community

#2574 enable passing docker-gid in helm chart
  charts/actions-runner-controller/templates/deployment.yaml
  charts/actions-runner-controller/values.yaml
Labels: needs triage, community

#2549 Use head_branch metric
  controllers/actions.summerwind.net/autoscaling.go
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook.go
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook_test.go
  controllers/actions.summerwind.net/integration_test.go
  controllers/actions.summerwind.net/runner_graceful_stop.go
  github/fake/runners.go
  github/github.go
  github/github_test.go
  go.mod
  go.sum
  pkg/actionsmetrics/event_reader.go
  pkg/actionsmetrics/metrics.go
  pkg/actionsmetrics/webhookserver.go
  pkg/githubwebhookdeliveryforwarder/githubwebhookdelivery.go
  pkg/hookdeliveryforwarder/forwarder.go
  pkg/hookdeliveryforwarder/hooks.go
  pkg/hookdeliveryforwarder/hooks_deliveries.go
  pkg/hookdeliveryforwarder/multiforwarder.go
  simulator/runnergroups.go
  test/e2e/e2e_test.go
Labels: needs triage, community

#2502 Update unconsumed HRA capacity reservation's expiration more frequently and consistently
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_batch_scale.go
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_batch_scale_test.go
  controllers/actions.summerwind.net/horizontal_runner_autoscaler_webhook_test.go
  docs/automatically-scaling-runners.md
Labels: needs triage, community
