Repository actions/actions-runner-controller, pull requests merged in 2023-01, with the labels that each got.

#2114 Restructure documentation
  README.md
  docs/about-arc.md
  docs/authenticating-to-the-github-api.md
  docs/automatically-scaling-runners.md
  docs/choosing-runner-destination.md
  docs/configuring-windows-runners.md
  docs/deploying-alternative-runners.md
  docs/deploying-arc-runners.md
  docs/detailed-docs.md
  docs/installing-arc.md
  docs/managing-access-with-runner-groups.md
  docs/monitoring-and-troubleshooting.md
  docs/quickstart.md
  docs/using-arc-across-organizations.md
  docs/using-arc-runners-in-a-workflow.md
  docs/using-custom-volumes.md
  docs/using-entrypoint-features.md
Labels: documentation

#2167 Create publish-arc2.yaml
  .github/workflows/publish-arc2.yaml
Labels: enhancement

#2168 Introduce new helm charts for the preview auto-scaling mode for ARC.
  Makefile
  charts/actions-runner-controller-2/.helmignore
  charts/actions-runner-controller-2/Chart.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_autoscalinglisteners.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_autoscalingrunnersets.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_ephemeralrunners.yaml
  charts/actions-runner-controller-2/crds/actions.github.com_ephemeralrunnersets.yaml
  charts/actions-runner-controller-2/templates/NOTES.txt
  charts/actions-runner-controller-2/templates/_helpers.tpl
  charts/actions-runner-controller-2/templates/deployment.yaml
  charts/actions-runner-controller-2/templates/leader_election_role.yaml
  charts/actions-runner-controller-2/templates/leader_election_role_binding.yaml
  charts/actions-runner-controller-2/templates/manager_role.yaml
  charts/actions-runner-controller-2/templates/manager_role_binding.yaml
  charts/actions-runner-controller-2/templates/serviceaccount.yaml
  charts/actions-runner-controller-2/tests/template_test.go
  charts/actions-runner-controller-2/values.yaml
  charts/auto-scaling-runner-set/.helmignore
  charts/auto-scaling-runner-set/Chart.yaml
  charts/auto-scaling-runner-set/ci/ci-values.yaml
  charts/auto-scaling-runner-set/templates/NOTES.txt
  charts/auto-scaling-runner-set/templates/_helpers.tpl
  charts/auto-scaling-runner-set/templates/autoscalingrunnerset.yaml
  charts/auto-scaling-runner-set/templates/githubsecret.yaml
  charts/auto-scaling-runner-set/templates/kube_mode_role.yaml
  charts/auto-scaling-runner-set/templates/kube_mode_role_binding.yaml
  charts/auto-scaling-runner-set/templates/kube_mode_serviceaccount.yaml
  charts/auto-scaling-runner-set/templates/no_permission_serviceaccount.yaml
  charts/auto-scaling-runner-set/tests/template_test.go
  charts/auto-scaling-runner-set/values.yaml
Labels: enhancement

#2093 Add Repository information to Runner Status
  apis/actions.summerwind.net/v1alpha1/runner_types.go
  apis/actions.summerwind.net/v1alpha1/zz_generated.deepcopy.go
  charts/actions-runner-controller/crds/actions.summerwind.dev_runners.yaml
  config/crd/bases/actions.summerwind.dev_runners.yaml
  runner/update-status
Labels: needs triage

#2214 Fix intermittent image push failures to GHCR
  .github/workflows/publish-arc2.yaml
Labels: bug

#2148 Fix some typo and markdown in troubleshooting guide
  TROUBLESHOOTING.md
Labels: documentation

#2223 Delete RunnerScaleSet on service when AutoScalingRunnerSet is deleted.
  controllers/actions.github.com/autoscalingrunnerset_controller.go
  controllers/actions.github.com/autoscalingrunnerset_controller_test.go
  github/actions/client.go
  github/actions/client_runner_scale_set_test.go
  github/actions/fake/client.go
  github/actions/mock_ActionsService.go
Labels: needs triage
