Repository actions/actions-runner-controller, pull requests merged in 2023-07, with the labels that each got.

#2682 Fix serviceMonitor labels in actionsMetrics
  charts/actions-runner-controller/templates/actionsmetrics.servicemonitor.yaml.yml
Labels: needs triage, community

#2713 chore: Set build version on make-runscaleset
  Makefile
Labels: gha-runner-scale-set

#2686 Add configurable log format to values.yaml and propagate it to listener
  charts/gha-runner-scale-set-controller/templates/deployment.yaml
  charts/gha-runner-scale-set-controller/tests/template_test.go
  charts/gha-runner-scale-set-controller/values.yaml
  cmd/githubrunnerscalesetlistener/main.go
  controllers/actions.github.com/constants.go
  controllers/actions.github.com/resourcebuilder.go
  main.go
Labels: gha-runner-scale-set

#2699 Add status check before deserializing runner-registration response
  github/actions/client.go
  github/actions/github_api_request_test.go
  github/actions/testserver/server.go
Labels: attention, gha-runner-scale-set

#2671 fix: remove callbacks resulting in scales due to incomplete response
  controllers/actions.summerwind.net/autoscaling.go
  controllers/actions.summerwind.net/autoscaling_test.go
Labels: needs triage, community

#2683 Fix deployment & service values in actionsMetrics
  charts/actions-runner-controller/templates/actionsmetrics.deployment.yaml
  charts/actions-runner-controller/templates/actionsmetrics.service.yaml
Labels: needs triage, community

#2708 add opportunity write dnsPolicy for controller by helm values
  charts/actions-runner-controller/README.md
  charts/actions-runner-controller/templates/deployment.yaml
  charts/actions-runner-controller/values.yaml
Labels: needs triage, community

#2654 add interval and timeout configuration for the actions-runner-controler serviceMonitors
  charts/actions-runner-controller/README.md
  charts/actions-runner-controller/templates/actionsmetrics.service.yaml
  charts/actions-runner-controller/templates/actionsmetrics.servicemonitor.yaml.yml
  charts/actions-runner-controller/templates/controller.metrics.serviceMonitor.yaml
  charts/actions-runner-controller/templates/githubwebhook.service.yaml
  charts/actions-runner-controller/templates/githubwebhook.serviceMonitor.yaml
  charts/actions-runner-controller/values.yaml
Labels: needs triage, community

#2701 feat: allow more dockerd options
  docs/using-entrypoint-features.md
  runner/actions-runner-dind-rootless.ubuntu-20.04.dockerfile
  runner/actions-runner-dind-rootless.ubuntu-22.04.dockerfile
  runner/entrypoint-dind-rootless.sh
Labels: needs triage, community
